# Change 'comments' to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: "millennial-3"

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-ID: "UA-112060364-2"

menu:
  - { name: "소개글", url: "about" }
  - { name: "헝가리", url: "resources" }
  - { name: "체코", url: "sample-posts" }
  - { name: "오스트리아", url: "documentation" }
  - { name: "음식", url: "facts" }
  - { name: "마무리", url: "contact" }

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
  - { icon: "instagram", link: "https://instagram.com/jjung._.you" }
  - { icon: "envelope", link: "mailto:y2ll5wxxx@naver.com" }

# Customize site text
pagination:
  next_page: "Newer"
  previous_page: "Older"

sharing_button_prompt: "Feel free to share!"

related_posts: "꽌련글"

post_date_prefix: "Written on"
